const products = [
  {
    id: 1,
    name: "Solar Panel Kit",
    price: 499,
    discount: 10, // 10% discount
    stock: 100, // 100 kits left in stock
    image: "https://i.ebayimg.com/images/g/GRcAAOSwAvlijHFE/s-l960.jpg",
    description: "High-efficiency solar panel kit for home and commercial use.",
    specifications: {
      powerOutput: "300W",
      efficiency: "20%",
      warranty: "25 years",
      features: ["Weatherproof", "Easy Installation", "High Efficiency"],
    },
    date: "2024-01-15",
    installments: [
      { months: 3, monthlyPayment: (499 * 0.9) / 3 }, // 3-month plan (after discount)
      { months: 6, monthlyPayment: (499 * 0.9) / 6 }, // 6-month plan (after discount)
      { months: 12, monthlyPayment: (499 * 0.9) / 12}, //12-month plan
    ],
  },
  {
    id: 2,
    name: "Lithium-Ion Battery",
    price: 299,
    discount: 5, // 5% discount
    stock: 75, // 75 units left in stock
    image: "https://d3f7dpm96o8eu9.cloudfront.net/media/wysiwyg/Blog/59936115_2372813869407905_6412893490170036224_o.jpg",
    description: "Long-lasting lithium-ion battery for solar storage.",
    specifications: {
      capacity: "5kWh",
      cycles: "5000+",
      weight: "25kg",
      features: ["Smart Monitoring", "Compact Design", "Deep Discharge"],
    },
    date: "2023-12-10",
    installments: [
      { months: 3, monthlyPayment: (299 * 0.95) / 3 },
      { months: 6, monthlyPayment: (299 * 0.95) / 6 },
      { months: 12, monthlyPayment: (299 * 0.95) / 12 },
    ],
  },
  {
    id: 3,
    name: "Pure Sine Wave Inverter",
    price: 399,
    discount: 15, // 15% discount
    stock: 50, // 50 units left in stock
    image: "https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/42/4072104/1.jpg?9929",
    description: "High-quality pure sine wave inverter for seamless power conversion.",
    specifications: {
      powerRating: "3000W",
      efficiency: "95%",
      cooling: "Fan-based",
      features: ["Quiet Operation", "Overload Protection", "Surge Protection"],
    },
    date: "2024-02-01",
    installments: [
      { months: 3, monthlyPayment: (399 * 0.85) / 3 },
      { months: 6, monthlyPayment: (399 * 0.85) / 6 },
      { months: 12, monthlyPayment: (399 * 0.85) / 12},
    ],
  },
  {
    id: 4,
    name: "Portable Solar Generator",
    price: 699,
    discount: 0, // No discount
    stock: 30, // 30 units left in stock
    image: "https://www-konga-com-res.cloudinary.com/w_400,f_auto,fl_lossy,dpr_auto,q_auto/media/catalog/product/Q/H/75657_1525936663.jpg",
    description: "Compact solar generator for camping and outdoor adventures.",
    specifications: {
      capacity: "1000Wh",
      inputPower: "150W",
      outputPower: "800W",
      features: ["USB Ports", "AC Outlets", "LED Lighting"],
    },
    date: "2024-01-22",
    installments: [
      { months: 3, monthlyPayment: 699 / 3 },
      { months: 6, monthlyPayment: 699 / 6 },
      { months: 12, monthlyPayment: 699/12},
    ],
  },
  {
    id: 5,
    name: "Solar Water Heater",
    price: 799,
    discount: 20, // 20% discount
    stock: 25, // 25 units left in stock
    image: "https://powersolutionmall.com/storage/2022/06/100-Lter-Solar-water-heater.jpg",
    description: "Energy-efficient solar water heater for residential use.",
    specifications: {
      capacity: "200L",
      material: "Stainless Steel",
      insulation: "Polyurethane Foam",
      features: ["Anti-freeze", "Durable", "Low Maintenance"],
    },
    date: "2024-02-05",
    installments: [
      { months: 3, monthlyPayment: (799 * 0.8) / 3 },
      { months: 6, monthlyPayment: (799 * 0.8) / 6 },
      { months: 12, monthlyPayment: (799 * 0.8) / 12},
    ],
  },
  {
    id: 6,
    name: "Solar Street Light",
    price: 449,
    discount: 10, // 10% discount
    stock: 60, // 60 units left in stock
    image: "https://i.ebayimg.com/images/g/DJEAAOSwEUtnGRoM/s-l960.jpg",
    description: "Solar-powered street light with motion detection.",
    specifications: {
      brightness: "5000 Lumens",
      batteryLife: "12 hours",
      connectivity: "Motion Sensor",
      features: ["Auto On/Off", "Remote Control", "Waterproof"],
    },
    date: "2024-01-30",
    installments: [
      { months: 3, monthlyPayment: (449 * 0.9) / 3 },
      { months: 6, monthlyPayment: (449 * 0.9) / 6 },
      { months: 12, monthlyPayment: (449 * 0.9) / 12},
    ],
  },
  {
    id: 7,
    name: "Home Energy Storage System",
    price: 1299,
    discount: 5, // 5% discount
    stock: 15, // 15 units left in stock
    image: "https://www.lithium-battery-factory.com/wp-content/uploads/2023/05/home-energy-storage-system.jpg",
    description: "Advanced energy storage system for homes.",
    specifications: {
      capacity: "10kWh",
      chargeTime: "4 hours",
      compatibility: "Solar Panels",
      features: ["Smart App Control", "Backup Power", "Expandable"],
    },
    date: "2024-02-03",
    installments: [
      { months: 3, monthlyPayment: (1299 * 0.95) / 3 },
      { months: 6, monthlyPayment: (1299 * 0.95) / 6 },
      { months: 12, monthlyPayment: (1299 * 0.95) / 12},
    ],
  },
  {
    id: 8,
    name: "Solar-Powered Fan",
    price: 149,
    discount: 0, // No discount
    stock: 100, // 100 units left in stock
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjjfFp-Hlw9_EzHiBPTsjVaDwgQimgEhDNWg&s",
    description: "Eco-friendly solar-powered fan for indoor and outdoor use.",
    specifications: {
      size: "12-inch",
      powerSource: "Solar Panel",
      features: ["Adjustable Speed", "Noiseless Operation", "Rechargeable Battery"],
    },
    date: "2024-01-29",
    installments: [
      { months: 3, monthlyPayment: 149 / 3 },
      { months: 6, monthlyPayment: 149 / 6 },
      { months: 12, monthlyPayment: 149/12},
    ],
  },
  {
    id: 9,
    name: "Solar Phone Charger",
    price: 59,
    discount: 15, // 15% discount
    stock: 200, // 200 units left in stock
    image: "https://images-cdn.ubuy.co.in/65cc3cb75b8e111e043a698a-bigblue-10w-etfe-solar-panel-charger.jpg",
    description: "Compact solar phone charger for on-the-go charging.",
    specifications: {
      capacity: "5000mAh",
      inputPower: "2W",
      features: ["USB Output", "Lightweight", "Waterproof"],
    },
    date: "2024-01-17",
    installments: [
      { months: 3, monthlyPayment: (59 * 0.85) / 3 },
      { months: 6, monthlyPayment: (59 * 0.85) / 6 },
      { months: 12, monthlyPayment: (59 * 0.85) / 12},
    ],
  },
  {
    id: 10,
    name: "Hybrid Inverter",
    price: 899,
    discount: 10, // 10% discount
    stock: 40, // 40 units left in stock
    image: "https://cdn.prod.website-files.com/62d9fdb180261014e2020876/62da526c754c765220afc272_SOLAR_NXG%2B1500VA2.png",
    description: "Hybrid inverter for solar and grid integration.",
    specifications: {
      powerRating: "5000W",
      efficiency: "96%",
      modes: ["Solar Mode", "Grid Mode", "Battery Mode"],
      features: ["MPPT Technology", "Real-time Monitoring", "Grid Support"],
    },
    date: "2024-01-12",
    installments: [
      { months: 3, monthlyPayment: (899 * 0.9) / 3 },
      { months: 6, monthlyPayment: (899 * 0.9) / 6 },
      { months: 12, monthlyPayment: (899 * 0.9) / 12},
    ],
  },
  {
    id: 2,
    name: "Solar Panel Cleaning Kit",
    price: 49,
    discount: 0,
    stock: 200,
    image: "https://s.alicdn.com/@sc04/kf/Hbd0ad74e7f9f483595cfc70d1fa304174.jpg_720x720q50.jpg",
    description: "Essential kit for maintaining solar panel efficiency.",
    specifications: {
      kitContents: ["Brush", "Squeegee", "Cleaning Solution", "Microfiber Cloth"],
      solutionType: "Biodegradable",
      features: ["Streak-Free", "Easy to Use", "Safe for Panels"],
    },
    date: "2024-03-15",
    installments: [
      { months: 3, monthlyPayment: 49 / 3 },
      { months: 6, monthlyPayment: 49 / 6 },
      { months: 12, monthlyPayment: 49 / 12 },
    ],
  },
  {
    id: 3,
    name: "Solar Powered Bluetooth Speaker",
    price: 79,
    discount: 10,
    stock: 100,
    image: "https://c1.neweggimages.com/productimage/nb640/VDVYD24050905SRI436.jpg",
    description: "Portable speaker that charges via solar energy.",
    specifications: {
      batteryLife: "15 hours",
      connectivity: "Bluetooth 5.0",
      waterResistance: "IPX6",
      features: ["Built-in Mic", "Solar Charging", "Outdoor Ready"],
    },
    date: "2024-03-20",
    installments: [
      { months: 3, monthlyPayment: (79 * 0.9) / 3 },
      { months: 6, monthlyPayment: (79 * 0.9) / 6 },
      { months: 12, monthlyPayment: (79 * 0.9) / 12 },
    ],
  },
  {
    id: 4,
    name: "Solar Flood Light",
    price: 89,
    discount: 0,
    stock: 80,
    image: "https://m.media-amazon.com/images/I/813xCJhODEL._AC_SL1500_.jpg",
    description: "Powerful solar-powered flood light for outdoor security.",
    specifications: {
      brightness: "2000 Lumens",
      batteryLife: "10 hours",
      detectionRange: "15m",
      features: ["Motion Sensor", "Waterproof", "Adjustable Mount"],
    },
    date: "2024-03-25",
    installments: [
      { months: 3, monthlyPayment: 89 / 3 },
      { months: 6, monthlyPayment: 89 / 6 },
      { months: 12, monthlyPayment: 89 / 12 },
    ],
  },
  {
    id: 5,
    name: "Solar Panel Mounting Brackets",
    price: 69,
    discount: 5,
    stock: 120,
    image: "https://images.squarespace-cdn.com/content/v1/6004afb33753c24df2462d5d/1640698270728-XJXXUXMY754BATDJ08XR/Triangle+bracket+2.jpg?format=1000w",
    description: "Sturdy mounting brackets for easy solar panel installation.",
    specifications: {
      material: "Aluminum",
      compatibility: "All Panel Sizes",
      features: ["Adjustable Angle", "Rust-Resistant", "Easy Assembly"],
    },
    date: "2024-03-30",
    installments: [
      { months: 3, monthlyPayment: (69 * 0.95) / 3 },
      { months: 6, monthlyPayment: (69 * 0.95) / 6 },
      { months: 12, monthlyPayment: (69 * 0.95) / 12 },
    ],
  },
  {
    id: 6,
    name: "Solar String Lights",
    price: 35,
    discount: 0,
    stock: 250,
    image: "https://images-cdn.ubuy.co.in/63f9236db43a3d494e74d0f3-joomer-solar-string-lights-garden-72ft.jpg",
    description: "Decorative solar-powered string lights for outdoor ambiance.",
    specifications: {
      length: "20ft",
      LEDCount: "50 LEDs",
      lightColor: "Warm White",
      features: ["Waterproof", "Auto On/Off", "Multiple Modes"],
    },
    date: "2024-04-05",
    installments: [
      { months: 3, monthlyPayment: 35 / 3 },
      { months: 6, monthlyPayment: 35 / 6 },
      { months: 12, monthlyPayment: 35 / 12 },
    ],
  },
  {
    id: 7,
    name: "Solar Powered Water Fountain",
    price: 149,
    discount: 10,
    stock: 60,
    image: "https://www.festive-lights.com/media/catalog/product/cache/c92ed59c59475eb177634379eeb07fa5/1/1/1175003_2.jpg",
    description: "Elegant solar fountain for gardens and patios.",
    specifications: {
      flowRate: "150 GPH",
      material: "Polyresin",
      features: ["Multiple Nozzles", "Easy Setup", "No Wiring"],
    },
    date: "2024-04-10",
    installments: [
      { months: 3, monthlyPayment: (149 * 0.9) / 3 },
      { months: 6, monthlyPayment: (149 * 0.9) / 6 },
      { months: 12, monthlyPayment: (149 * 0.9) / 12 },
    ],
  },
  {
    id: 8,
    name: "Solar Deck Lights",
    price: 45,
    discount: 0,
    stock: 180,
    image: "https://m.media-amazon.com/images/I/51OOv6Fq97L.jpg",
    description: "Solar-powered lights for decks, stairs, and pathways.",
    specifications: {
      brightness: "50 Lumens",
      batteryLife: "8 hours",
      features: ["Durable", "Weatherproof", "Easy Installation"],
    },
    date: "2024-04-15",
    installments: [
      { months: 3, monthlyPayment: 45 / 3 },
      { months: 6, monthlyPayment: 45 / 6 },
      { months: 12, monthlyPayment: 45 / 12 },
    ],
  },
  {
    id: 9,
    name: "Solar Security Light with Camera",
    price: 249,
    discount: 15,
    stock: 30,
    image: "https://www.suluway.ng/wp-content/uploads/2024/10/IMG-20230413-WA0059.jpg",
    description: "Advanced solar light with built-in security camera.",
    specifications: {
      resolution: "1080p HD",
      batteryLife: "3 months",
      storage: "Cloud/SD Card",
      features: ["Motion Alerts", "Night Vision", "Two-Way Audio"],
    },
    date: "2024-04-20",
    installments: [
      { months: 3, monthlyPayment: (249 * 0.85) / 3 },
      { months: 6, monthlyPayment: (249 * 0.85) / 6 },
      { months: 12, monthlyPayment: (249 * 0.85) / 12 },
    ],
  },
  {
    id: 10,
    name: "Portable Solar Power Bank",
    price: 69,
    discount: 0,
    stock: 220,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoI4MWTL-zOLedsAthZffcQgQawnoQ6vvDVQ&s",
    description: "High-capacity power bank with solar charging capabilities.",
    specifications: {
      capacity: "20000mAh",
      output: "Dual USB",
      features: ["LED Flashlight", "Water-Resistant", "Fast Charging"],
    },
    date: "2024-04-25",
    installments: [
      { months: 3, monthlyPayment: 69 / 3 },
      { months: 6, monthlyPayment: 69 / 6 },
      { months: 12, monthlyPayment: 69 / 12 },
    ],
  },
    {
        id: 11,
        name: "Solar Car Battery Charger",
        price: 99,
        discount: 5,
        stock: 75,
        image: "https://static.wixstatic.com/media/093405_9041b76276b142039467c840a595db8c~mv2.jpg/v1/fill/w_568,h_512,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/093405_9041b76276b142039467c840a595db8c~mv2.jpg",
        description: "Maintain your car battery charge with this solar trickle charger.",
        specifications: {
          powerOutput: "12V",
          cableLength: "10ft",
          features: ["Overcharge Protection", "Easy Connection", "Weatherproof"],
        },
        date: "2024-05-01",
        installments: [
          { months: 3, monthlyPayment: (99 * 0.95) / 3 },
          { months: 6, monthlyPayment: (99 * 0.95) / 6 },
          { months: 12, monthlyPayment: (99 * 0.95) / 12 },
        ],
      },
      {
        id: 12,
        name: "Solar Camping Shower",
        price: 59,
        discount: 0,
        stock: 130,
        image: "https://cdn11.bigcommerce.com/s-pusehjx/images/stencil/1280x1280/products/6560/17303/3_Gallon_12L_Portable_Camping_Pressure_Solar_Shower_1__66699.1638828093.jpg?c=2",
        description: "Portable solar-heated shower for camping and outdoor activities.",
        specifications: {
          capacity: "5 Gallons",
          material: "PVC",
          features: ["Temperature Gauge", "On/Off Valve", "Compact Design"],
        },
        date: "2024-05-05",
        installments: [
          { months: 3, monthlyPayment: 59 / 3 },
          { months: 6, monthlyPayment: 59 / 6 },
          { months: 12, monthlyPayment: 59 / 12 },
        ],
      },
      {
        id: 13,
        name: "Solar Powered Keyboard",
        price: 75,
        discount: 10,
        stock: 90,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5FAVaMknXZ419JSFCDemdet0GOSjySOqjgQ&s",
        description: "Eco-friendly wireless keyboard that charges via solar power.",
        specifications: {
          connectivity: "Bluetooth/2.4GHz Wireless",
          batteryLife: "Unlimited with Sunlight",
          features: ["Slim Design", "Quiet Keys", "Rechargeable Battery"],
        },
        date: "2024-05-10",
        installments: [
          { months: 3, monthlyPayment: (75 * 0.9) / 3 },
          { months: 6, monthlyPayment: (75 * 0.9) / 6 },
          { months: 12, monthlyPayment: (75 * 0.9) / 12 },
        ],
      },
      {
        id: 14,
        name: "Solar Landscape Spotlights",
        price: 55,
        discount: 0,
        stock: 160,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLOsfLC0cXqAQG6lSZcVO-D7A3AyTEQnAUqQ&s",
        description: "Accentuate your garden features with solar-powered spotlights.",
        specifications: {
          brightness: "200 Lumens",
          lightColor: "White/Warm White",
          features: ["Adjustable Head", "Waterproof", "Stake Mount"],
        },
        date: "2024-05-15",
        installments: [
          { months: 3, monthlyPayment: 55 / 3 },
          { months: 6, monthlyPayment: 55 / 6 },
          { months: 12, monthlyPayment: 55 / 12 },
        ],
      },
      {
        id: 15,
        name: "Solar Garden Gnomes",
        price: 29,
        discount: 5,
        stock: 210,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQy4sFGFhXGRmz7aSRrW1NIpbLqf89KLLtRNw&s",
        description: "Charming solar-powered garden gnomes with LED lights.",
        specifications: {
          material: "Resin",
          lightColor: "Warm White",
          features: ["Waterproof", "Hand-Painted", "Whimsical Design"],
        },
        date: "2024-05-20",
        installments: [
          { months: 3, monthlyPayment: (29 * 0.95) / 3 },
          { months: 6, monthlyPayment: (29 * 0.95) / 6 },
          { months: 12, monthlyPayment: (29 * 0.95) / 12 },
        ],
      },
      {
        id: 16,
        name: "Solar Powered Mouse",
        price: 40,
        discount: 0,
        stock: 100,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTP15fL--hcFiZflXg705cOSeSfWq_ptiAd5A&s",
        description: "Wireless computer mouse that recharges through solar power.",
        specifications: {
          connectivity: "Bluetooth/USB",
          features: ["Ergonomic Design", "Rechargeable Battery", "Solar Charging"],
        },
        date: "2024-05-25",
        installments: [
          { months: 3, monthlyPayment: 40 / 3 },
          { months: 6, monthlyPayment: 40 / 6 },
          { months: 12, monthlyPayment: 40 / 12 },
        ],
      },
];

export default products;
